title: QLSC 612 - Foundations of Neuro Data Science
description: An introduction to the foundations of neuro data science
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

github:
  repository_url: https://neurodatascience.github.io/QLS612-Overview/
