---
on:
    push:
    pull_request:
        types: [opened, synchronize]
jobs:
    build:
        if: github.repository == 'neurodatascience/QLS612-Overview'
        runs-on: ubuntu-latest
        name: script/cibuild
        steps:
        -   uses: actions/checkout@v2
        -   uses: ruby/setup-ruby@v1
            with:
                ruby-version: 3.0
                bundler-cache: true
        -   name: build
            run: script/bootstrap
        -   name: test
            run: script/cibuild
